/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ensisa.hassenforder.golfinettes.admin.ui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import fr.ensisa.hassenforder.golfinettes.admin.model.Event;
import fr.ensisa.hassenforder.golfinettes.admin.model.Golfinette;
import fr.ensisa.hassenforder.golfinettes.admin.model.ModelListener;

/**
 *
 * @author Hassenforder
 */
public class Admin_UI extends javax.swing.JFrame implements ModelListener {

    private GUIListener listener;

    /**
     * Creates new form Golfinette
     */
    public Admin_UI() {
        initComponents();
    }
    
    public void setListener(GUIListener listener) {
        this.listener = listener;
    }
    
    @Override
    public void notifyStatusChanged (String status) {
        jStatus.setText(status);
    }

    @Override
    public void notifyMapVersionChanged (String version) {
        jVersionMap.setText(version);
    }

    @Override
    public void notifySoftwareVersionChanged (String version) {
        jVersionSoftware.setText(version);
    }

    @Override
    public void notifyUsersVersionChanged (String version) {
        jVersionUsers.setText(version);
    }

	@Override
	public void notifyEventListChanged(List<Event> events) {
		if (events != null) {
			List<Event> arePresent = new ArrayList<Event>();
			List<Component> toRemove = new ArrayList<Component>();
	
			for (Component c : jEvents.getComponents()) {
				if (!(c instanceof Event_UI)) continue;
				Event_UI e = (Event_UI) c;
				if (events.contains(e.getEvent())) arePresent.add(e.getEvent());
				else toRemove.add(c);
			}
			for (Component c : toRemove) {
				jEvents.remove(c);
			}
			toRemove = null;
			
			List<Event> toAdd = new ArrayList<Event>();
			for (Event e : events) {
				if (! arePresent.contains(e)) toAdd.add(e);
			}
			arePresent = null;
	
			for (Event e : toAdd) {
				jEvents.add(new Event_UI(e));
			}
			toAdd = null;
	
		}
		jEvents.revalidate();
		jEvents.repaint();
	}

	@Override
	public void notifyGolfinetteListChanged(List<Golfinette> golfinettes) {
		if (golfinettes != null) {
			List<Golfinette> arePresent = new ArrayList<Golfinette>();
			List<Component> toRemove = new ArrayList<Component>();
	
			for (Component c : jGolfinettes.getComponents()) {
				if (!(c instanceof Golfinette_UI)) continue;
				Golfinette_UI g = (Golfinette_UI) c;
				if (golfinettes.contains(g.getGolfinette())) arePresent.add(g.getGolfinette());
				else toRemove.add(c);
			}
			for (Component c : toRemove) {
				jGolfinettes.remove(c);
			}
			toRemove = null;
			
			List<Golfinette> toAdd = new ArrayList<Golfinette>();
			for (Golfinette g : golfinettes) {
				if (! arePresent.contains(g)) toAdd.add(g);
			}
			arePresent = null;
	
			for (Golfinette g : toAdd) {
				jGolfinettes.add(new Golfinette_UI(g));
			}
			toAdd = null;
		}
		jGolfinettes.revalidate();
		jGolfinettes.repaint();
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jVersionSoftware = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jVersionMap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jVersionUsers = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jGetGolfinettes = new javax.swing.JButton();
        jClearGolfinettes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jGolfinettes = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jGetEvents = new javax.swing.JButton();
        jClearEvents = new javax.swing.JButton();
        jId = new javax.swing.JTextField();
        jKind = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEvents = new javax.swing.JPanel();
        jStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Versions");

        jLabel3.setText("Software");

        jVersionSoftware.setText("V1.0");
        jVersionSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVersionSoftwareActionPerformed(evt);
            }
        });

        jLabel4.setText("Map");

        jVersionMap.setText("V1.0");
        jVersionMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVersionMapActionPerformed(evt);
            }
        });

        jLabel5.setText("User");

        jVersionUsers.setText("V1.0");
        jVersionUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVersionUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVersionSoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVersionMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVersionUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel3)
                        .addComponent(jVersionSoftware)
                        .addComponent(jLabel4)
                        .addComponent(jVersionMap)
                        .addComponent(jLabel5)
                        .addComponent(jVersionUsers)
                        .addComponent(jLabel13)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Golfinettes");

        jGetGolfinettes.setText("GetAll");
        jGetGolfinettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetGolfinettesActionPerformed(evt);
            }
        });

        jClearGolfinettes.setText("Clear");
        jClearGolfinettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearGolfinettesActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jGolfinettes.setLayout(new javax.swing.BoxLayout(jGolfinettes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jGolfinettes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jClearGolfinettes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGetGolfinettes)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jGetGolfinettes)
                    .addComponent(jClearGolfinettes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jLabel21.setText("Events");

        jGetEvents.setText("Get");
        jGetEvents.setActionCommand("");
        jGetEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetEventsActionPerformed(evt);
            }
        });

        jClearEvents.setText("Clear");
        jClearEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearEventsActionPerformed(evt);
            }
        });

        jId.setText("-1");
        jId.setToolTipText("Id of golfinette or -1 for all");

        jKind.setText("");
        jKind.setToolTipText("kind of event (wifi, sigfox, etc");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jKind, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGetEvents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jClearEvents)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGetEvents)
                    .addComponent(jClearEvents)
                    .addComponent(jLabel21)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jEvents.setLayout(new javax.swing.BoxLayout(jEvents, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jEvents);

        jStatus.setText("jStatus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jStatus))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVersionSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:jVersionSoftwareActionPerformed
    	if (listener != null) listener.onVersionSoftware();
    }//GEN-LAST:event_jVersionSoftwareActionPerformed

    private void jVersionMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVersionMapActionPerformed
    	if (listener != null) listener.onVersionMap();
    }//GEN-LAST:event_jVersionMapActionPerformed

    private void jVersionUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVersionUsersActionPerformed
    	if (listener != null) listener.onVersionUsers();
    }//GEN-LAST:event_jVersionUsersActionPerformed

    private void jClearEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearEventsActionPerformed
    	if (listener != null) listener.onClearEventList();
    }//GEN-LAST:event_jClearEventsActionPerformed

    private void jGetEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetEventsActionPerformed
    	long id = -1;
    	try { id = Long.parseLong(jId.getText()); } catch (Exception e) { }
    	String kind = jKind.getText();
    	if (listener != null) listener.onGetEventList(id, kind);
    }//GEN-LAST:event_jGetEventsActionPerformed

    private void jClearGolfinettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearGolfinettesActionPerformed
    	if (listener != null) listener.onClearGolfinetteList();
    }//GEN-LAST:event_jClearGolfinettesActionPerformed

    private void jGetGolfinettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetGolfinettesActionPerformed
    	if (listener != null) listener.onGetGolfinetteList();
    }//GEN-LAST:event_jGetGolfinettesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClearEvents;
    private javax.swing.JButton jClearGolfinettes;
    private javax.swing.JPanel jEvents;
    private javax.swing.JButton jGetGolfinettes;
    private javax.swing.JPanel jGolfinettes;
    private javax.swing.JTextField jId;
    private javax.swing.JTextField jKind;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jGetEvents;
    private javax.swing.JLabel jStatus;
    private javax.swing.JButton jVersionMap;
    private javax.swing.JButton jVersionSoftware;
    private javax.swing.JButton jVersionUsers;
    // End of variables declaration//GEN-END:variables
}
