package fr.ensisa.hassenforder.golfinettes.client.ui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import fr.ensisa.hassenforder.golfinettes.client.model.Battery;
import fr.ensisa.hassenforder.golfinettes.client.model.Event;
import fr.ensisa.hassenforder.golfinettes.client.model.Location;
import fr.ensisa.hassenforder.golfinettes.client.model.ModelListener;
import fr.ensisa.hassenforder.golfinettes.client.model.Usage;
import fr.ensisa.hassenforder.golfinettes.client.model.Battery.BatteryMode;
import fr.ensisa.hassenforder.golfinettes.client.model.Usage.BorrowerEvent;
import fr.ensisa.hassenforder.golfinettes.client.model.Usage.UsageState;

/**
 *
 * @author Hassenforder
 */
public class Golfinette_UI extends javax.swing.JFrame implements ModelListener {

    private GUIListener listener;

    /**
     * Creates new form Golfinette
     */
    public Golfinette_UI() {
        initComponents();
    }

    public void setListener(GUIListener listener) {
        this.listener = listener;
    }
    
    @Override
    public void notifyStatusChanged (String status) {
        jStatus.setText(status);
    }

    @Override
    public void notifyMapVersionChanged (String version) {
        jVersionMap.setText(version);
    }

    @Override
    public void notifySoftwareVersionChanged (String version) {
        jVersionSoftware.setText(version);
    }

    @Override
    public void notifyUsersVersionChanged (String version) {
        jVersionUsers.setText(version);
    }

	@Override
	public void notifyPositionChanged(float latitude, float longitude) {
		jLatitude.setText(Float.toString(latitude));
		jLongitude.setText(Float.toString(longitude));
	}

	@Override
	public void notifyAmbientChanged(int temperature, int humidity) {
		jLocalTemperature.setText(Integer.toString(temperature));
		jHumidity.setText(Integer.toString(humidity));
	}

	@Override
	public void notifyPowerChanged(int temperature, int load) {
		jPowerTemperature.setText(Integer.toString(temperature));
		jPowerLoad.setText(Integer.toString(load));
	}

	@Override
    public void notifyEventListChanged (List<Event> events) {
		List<Event> arePresent = new ArrayList<Event>();
		List<Component> toRemove = new ArrayList<Component>();

		for (Component c : jEvents.getComponents()) {
			if (!(c instanceof Event_UI)) continue;
			Event_UI e = (Event_UI) c;
			if (events.contains(e.getEvent())) arePresent.add(e.getEvent());
			else toRemove.add(c);
		}
		for (Component c : toRemove) {
			jEvents.remove(c);
		}
		toRemove = null;
		
		List<Event> toAdd = new ArrayList<Event>();
		for (Event e : events) {
			if (! arePresent.contains(e)) toAdd.add(e);
		}
		arePresent = null;

		for (Event e : toAdd) {
			jEvents.add(new Event_UI(listener, e));
		}
		toAdd = null;

		jEvents.revalidate();
		jEvents.repaint();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlugging = new javax.swing.ButtonGroup();
        jUserAction = new javax.swing.ButtonGroup();
        jState = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jVersionSoftware = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jVersionMap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jVersionUsers = new javax.swing.JLabel();
        jAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLongitude = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLatitude = new javax.swing.JTextField();
        jNextPosition = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLocalTemperature = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jHumidity = new javax.swing.JTextField();
        jNextAmbient = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPowerTemperature = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPowerLoad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jCharging = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        jDischarge = new javax.swing.JSlider();
        jPlugged = new javax.swing.JRadioButton();
        jSlow = new javax.swing.JRadioButton();
        jFast = new javax.swing.JRadioButton();
        jUnplugged = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jNextPower = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jKind = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jFree = new javax.swing.JRadioButton();
        jBorrow = new javax.swing.JRadioButton();
        jReturn = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jSN = new javax.swing.JRadioButton();
        jMN = new javax.swing.JRadioButton();
        jSL = new javax.swing.JRadioButton();
        jMB = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jDetail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSofwareUpdate = new javax.swing.JButton();
        jMapUpdate = new javax.swing.JButton();
        jUserUpdate = new javax.swing.JButton();
        jSigFox = new javax.swing.JButton();
        jWifi = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEvents = new javax.swing.JPanel();
        jStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("identities");

        jLabel1.setText("id");

        jId.setText("1");

        jLabel2.setText("Versions :");

        jLabel3.setText("Software");

        jVersionSoftware.setText("V0.0");

        jLabel4.setText("Map");

        jVersionMap.setText("V0.0");

        jLabel5.setText("User");

        jVersionUsers.setText("V0.0");

        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVersionSoftware)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVersionMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVersionUsers)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAdd)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jVersionSoftware)
                    .addComponent(jLabel4)
                    .addComponent(jVersionMap)
                    .addComponent(jLabel5)
                    .addComponent(jVersionUsers))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Position");

        jLabel6.setText("Longitude");

        jLongitude.setText("47.85");

        jLabel7.setText("Latitude");

        jLatitude.setText("7.557");

        jNextPosition.setText("Next");
        jNextPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextPositionActionPerformed(evt);
            }
        });

        jLabel8.setText("Temperature");

        jLocalTemperature.setText("25");

        jLabel9.setText("Humidity");

        jHumidity.setText("80");

        jNextAmbient.setText("Next");
        jNextAmbient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextAmbientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jNextPosition))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLocalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNextAmbient)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jNextPosition)
                    .addComponent(jLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jLocalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNextAmbient))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Power");

        jLabel10.setText("Temperature");

        jPowerTemperature.setText("28");

        jLabel11.setText("Load");

        jPowerLoad.setText("99");

        jLabel15.setText("Charging");
        jLabel15.setToolTipText("");

        jCharging.setMajorTickSpacing(1);
        jCharging.setMaximum(10);
        jCharging.setValue(2);

        jLabel16.setText("Discharge");
        jLabel16.setToolTipText("");

        jDischarge.setMajorTickSpacing(10);

        jPlugging.add(jUnplugged);
        jUnplugged.setText("Unplugged");
        jUnplugged.setSelected(true);

        jPlugging.add(jPlugged);
        jPlugged.setText("Plugged no charge");

        jPlugging.add(jSlow);
        jSlow.setText("Slow charge");

        jPlugging.add(jFast);
        jFast.setText("Fast charge");

        jLabel17.setText("Plugged");
        jLabel17.setToolTipText("");

        jNextPower.setText("Next");
        jNextPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextPowerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPowerTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPowerLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNextPower)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCharging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jUnplugged)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPlugged)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSlow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFast)))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jPowerTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jPowerLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNextPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jCharging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jUnplugged)
                    .addComponent(jPlugged)
                    .addComponent(jSlow)
                    .addComponent(jFast)
                    .addComponent(jLabel17))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Alarm");

        jLabel26.setText("Kind");
        jLabel26.setToolTipText("");

        jKind.setText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jKind, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("Usage");

        jUser.setText("");
        jUser.setToolTipText("Id borrower");

        jUserAction.add(jFree);
        jFree.setText("Free");
        jFree.setSelected(true);

        jUserAction.add(jBorrow);
        jBorrow.setText("Borrow");

        jUserAction.add(jReturn);
        jReturn.setText("Return");

        jLabel23.setText("State");

        jState.add(jSN);
        jSN.setText("Steady Normal");

        jState.add(jMN);
        jMN.setText("Moving Normal");

        jState.add(jSL);
        jSL.setText("Steady Long");
        jSL.setSelected(true);

        jState.add(jMB);
        jMB.setText("Moving Back");

        jLabel24.setText("Detail");

        jDetail.setText("");
        jDetail.setToolTipText("if available");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jUser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBorrow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jReturn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSN)
                            .addComponent(jSL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jMN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jMB)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jSN)
                            .addComponent(jMN)
                            .addComponent(jLabel23)
                            .addComponent(jDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSL)
                            .addComponent(jMB)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jBorrow)
                        .addComponent(jReturn)
                        .addComponent(jFree)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("Update");

        jSofwareUpdate.setText("Sofware");
        jSofwareUpdate.setActionCommand("");
        jSofwareUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSofwareUpdateActionPerformed(evt);
            }
        });

        jMapUpdate.setText("Map");
        jMapUpdate.setActionCommand("");
        jMapUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMapUpdateActionPerformed(evt);
            }
        });

        jUserUpdate.setText("User");
        jUserUpdate.setActionCommand("");
        jUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserUpdateActionPerformed(evt);
            }
        });

        jSigFox.setText("SigFox");
        jSigFox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSigFoxActionPerformed(evt);
            }
        });

        jWifi.setText("Wifi");
        jWifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWifiActionPerformed(evt);
            }
        });

        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jLabel22.setText("Event");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSofwareUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMapUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSigFox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jClear)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSofwareUpdate)
                    .addComponent(jSigFox)
                    .addComponent(jWifi)
                    .addComponent(jClear)
                    .addComponent(jMapUpdate)
                    .addComponent(jLabel21)
                    .addComponent(jUserUpdate)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jEvents.setLayout(new javax.swing.BoxLayout(jEvents, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jEvents);

        jStatus.setText("jStatus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jStatus))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSofwareUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSofwareUpdateActionPerformed
    	if (listener != null) listener.onDoSoftwareUpdate();
    }//GEN-LAST:event_jSofwareUpdateActionPerformed

    private void jUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserUpdateActionPerformed
    	if (listener != null) listener.onDoUsersUpdate();
    }//GEN-LAST:event_jUserUpdateActionPerformed

    private void jMapUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMapUpdateActionPerformed
    	if (listener != null) listener.onDoMapUpdate();
    }//GEN-LAST:event_jMapUpdateActionPerformed

    private void jSigFoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSigFoxActionPerformed
    	if (listener != null) listener.onDoSigFox();
    }//GEN-LAST:event_jSigFoxActionPerformed

    private void jWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWifiActionPerformed
    	if (listener != null) listener.onDoWifi();
    }//GEN-LAST:event_jWifiActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
    	if (listener != null) listener.onClearEventList();
    }//GEN-LAST:event_jClearActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
    	try {
    		long id = 0;
    		try { id = Long.parseLong(jId.getText()); } catch (Exception e) { }
    		
    		float latitude = 0.0F;
    		try { latitude = Float.parseFloat(jLatitude.getText()); } catch (Exception e) { }
    		float longitude = 0.0F;
    		try { longitude = Float.parseFloat(jLongitude.getText()); } catch (Exception e) { }
    		int localTemperature = 0;
    		try { localTemperature = Integer.parseInt(jLocalTemperature.getText()); } catch (Exception e) { }
    		int humidity = 0;
    		try { humidity = Integer.parseInt(jHumidity.getText()); } catch (Exception e) { }
    		Location location = new Location(latitude, longitude, localTemperature, humidity);

    		int powerTemperature = 0;
    		try { powerTemperature = Integer.parseInt(jPowerTemperature.getText()); } catch (Exception e) { }
    		int powerLoad = 0;
    		try { powerLoad = Integer.parseInt(jPowerLoad.getText()); } catch (Exception e) { }
    		int charging = jCharging.getValue();
    		int discharge = jDischarge.getValue();
    		BatteryMode mode = null;
    		if (jUnplugged.isSelected()) mode = BatteryMode.UNPLUGGED;
    		if (jPlugged.isSelected()) mode = BatteryMode.PLUGGED_ONLY;
    		if (jSlow.isSelected()) mode = BatteryMode.SLOW_CHARGING;
    		if (jFast.isSelected()) mode = BatteryMode.FAST_CHARGING;
    		Battery power = new Battery (powerTemperature, powerLoad, charging, discharge, mode);
    		
    		long borrower = 0;
    		try { borrower = Long.parseLong(jUser.getText()); } catch (Exception e) { }
			BorrowerEvent be = null;
			if (jFree.isSelected()) be = BorrowerEvent.FREE;
			if (jBorrow.isSelected()) be = BorrowerEvent.BORROW;
			if (jReturn.isSelected()) be = BorrowerEvent.RETURN;
			UsageState us = null;
			if (jSN.isSelected()) us = UsageState.STEADY_NORMAL;
			if (jSL.isSelected()) us = UsageState.STEADY_LONG;
			if (jMN.isSelected()) us = UsageState.MOVING_NORMAL;
			if (jMB.isSelected()) us = UsageState.MOVING_BACK;
    		int detail = 0;
    		try { detail = Integer.parseInt(jDetail.getText()); } catch (Exception e) { }
    		int alarm = 0;
    		try { alarm = Integer.parseInt(jKind.getText()); } catch (Exception e) { }
    		Usage usage = new Usage (borrower, be, us, detail, alarm);

    		Event event = new Event(id).withLocation(location).withBattery(power).withUsage(usage);
    		if (listener != null) listener.onAddEvent(event);
    	} catch (Exception e) {
    		
    	}
    }//GEN-LAST:event_jAddActionPerformed

    private void jNextPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextPositionActionPerformed
    	if (listener != null) listener.onNextPosition();
    }//GEN-LAST:event_jNextPositionActionPerformed

    private void jNextAmbientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextAmbientActionPerformed
    	if (listener != null) listener.onNextAmbient();
    }//GEN-LAST:event_jNextAmbientActionPerformed

    private void jNextPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextPowerActionPerformed
    	if (listener != null) listener.onNextPower();
    }//GEN-LAST:event_jNextPowerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JRadioButton jBorrow;
    private javax.swing.JSlider jCharging;
    private javax.swing.JButton jClear;
    private javax.swing.JTextField jDetail;
    private javax.swing.JSlider jDischarge;
    private javax.swing.JPanel jEvents;
    private javax.swing.JRadioButton jFree;
    private javax.swing.JTextField jHumidity;
    private javax.swing.JTextField jId;
    private javax.swing.JTextField jKind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLatitude;
    private javax.swing.JTextField jLocalTemperature;
    private javax.swing.JTextField jLongitude;
    private javax.swing.JRadioButton jMB;
    private javax.swing.JRadioButton jMN;
    private javax.swing.JButton jMapUpdate;
    private javax.swing.JButton jNextAmbient;
    private javax.swing.JButton jNextPosition;
    private javax.swing.JButton jNextPower;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.ButtonGroup jPlugging;
    private javax.swing.JTextField jPowerLoad;
    private javax.swing.JTextField jPowerTemperature;
    private javax.swing.JRadioButton jPlugged;
    private javax.swing.JRadioButton jSlow;
    private javax.swing.JRadioButton jFast;
    private javax.swing.JRadioButton jUnplugged;
    private javax.swing.JRadioButton jReturn;
    private javax.swing.JRadioButton jSL;
    private javax.swing.JRadioButton jSN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSigFox;
    private javax.swing.JButton jSofwareUpdate;
    private javax.swing.ButtonGroup jState;
    private javax.swing.JLabel jStatus;
    private javax.swing.JTextField jUser;
    private javax.swing.ButtonGroup jUserAction;
    private javax.swing.JButton jUserUpdate;
    private javax.swing.JLabel jVersionMap;
    private javax.swing.JLabel jVersionSoftware;
    private javax.swing.JLabel jVersionUsers;
    private javax.swing.JButton jWifi;
    // End of variables declaration//GEN-END:variables

}
